# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c2e75441cb29403afe520abb8ace496174e8d26d483ceeb4eda204f5442593fb3159f26b489956f73162f4b8f2422cb802336629b6641a743fc60ead1bb21f4b

test:
  secret_key_base: a3d3aa5493cbbde9192106c8a71b9e40703022825e15d6efc230f1bbda2f12cbc82ba9eb867665e446e8fbf5835acb7daf8fca886ffdef5bd81db01b9c077aa8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
